# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-12-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/punk.jpg', upload_to='profile_pics'),
        ),
    ]
